address=/jellyfin.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/torrserver.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/immich.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/vaultwarden.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/kuma.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/agent.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/it-tools.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/dozzle.home.arpa/${HOMELAB_HOST:-your_local_ip}
address=/homeassistant.home.arpa/${HOMELAB_HOST:-your_local_ip}
