services:
  caddy:
    image: caddy:2
    container_name: caddy
    networks: [homelab]
    ports: ["${HOMELAB_HOST:-your_local_ip}:443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
networks:
  homelab:
    external: true
volumes:
  caddy-data:
  caddy-config:
