version: "3.9"
services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    networks: [homelab]
    depends_on: [ jellyfin, qbittorrent, immich-server, vaultwarden, uptime-kuma, homelab-agent-web ]
    ports: [ "${HOMELAB_HOST:-your_local_ip}:80:80", "${HOMELAB_HOST:-your_local_ip}:443:443" ]
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    restart: unless-stopped
networks:
  homelab:
    external: true
